nn(ptsnet, [TS, P], H, [0, 1])::has_proto(TS, P, H).

0.75::has_proto(ts0, p0).
0.65::has_proto(ts0, p1).

0.75::has_proto(ts1, p0).
0.35::has_proto(ts1, p1).

0.05::has_proto(ts2, p0).
0.80::has_proto(ts2, p1).

t(_)::connected(p0, c0).
t(_)::connected(p1, c1).

% is_class(TS, c0) :- class(c0), has_proto(TS, p0).
% is_class(TS, c1) :- class(c1), has_proto(TS, p1).
is_class(TS, c0) :- class(c0), has_proto(TS, p0), connected(p0, c0).
is_class(TS, c1) :- class(c1), has_proto(TS, p1), connected(p1, c1).

class(c0).
class(c1).

query(is_class(ts0, c0)).
query(is_class(ts0, c1)).
query(is_class(ts1, c0)).
query(is_class(ts1, c1)).
query(is_class(ts2, c0)).
query(is_class(ts2, c1)).

% is_class(TS, c0) :- has_proto(TS, p0), connected(p0, c0), not(and(has_proto(TS, p1), connected(p1, c1))), not(and(has_proto(TS, p2), connected(p2, c2))), not(and(has_proto(TS, p3), connected(p3, c3))), not(and(has_proto(TS, p4), connected(p4, c4))), not(and(has_proto(TS, p5), connected(p5, c5))), not(and(has_proto(TS, p6), connected(p6, c6))), not(and(has_proto(TS, p7), connected(p7, c7))), not(and(has_proto(TS, p8), connected(p8, c8))), not(and(has_proto(TS, p9), connected(p9, c9))), not(and(has_proto(TS, p10), connected(p10, c10))), not(and(has_proto(TS, p11), connected(p11, c11))), not(and(has_proto(TS, p12), connected(p12, c12))), not(and(has_proto(TS, p13), connected(p13, c13))), not(and(has_proto(TS, p14), connected(p14, c14))).
% is_class(TS, c1) :- has_proto(TS, p1), connected(p1, c1), not(and(has_proto(TS, p0), connected(p0, c0))), not(and(has_proto(TS, p2), connected(p2, c2))), not(and(has_proto(TS, p3), connected(p3, c3))), not(and(has_proto(TS, p4), connected(p4, c4))), not(and(has_proto(TS, p5), connected(p5, c5))), not(and(has_proto(TS, p6), connected(p6, c6))), not(and(has_proto(TS, p7), connected(p7, c7))), not(and(has_proto(TS, p8), connected(p8, c8))), not(and(has_proto(TS, p9), connected(p9, c9))), not(and(has_proto(TS, p10), connected(p10, c10))), not(and(has_proto(TS, p11), connected(p11, c11))), not(and(has_proto(TS, p12), connected(p12, c12))), not(and(has_proto(TS, p13), connected(p13, c13))), not(and(has_proto(TS, p14), connected(p14, c14))).
% is_class(TS, c2) :- has_proto(TS, p2), connected(p2, c2), not(and(has_proto(TS, p0), connected(p0, c0))), not(and(has_proto(TS, p1), connected(p1, c1))), not(and(has_proto(TS, p3), connected(p3, c3))), not(and(has_proto(TS, p4), connected(p4, c4))), not(and(has_proto(TS, p5), connected(p5, c5))), not(and(has_proto(TS, p6), connected(p6, c6))), not(and(has_proto(TS, p7), connected(p7, c7))), not(and(has_proto(TS, p8), connected(p8, c8))), not(and(has_proto(TS, p9), connected(p9, c9))), not(and(has_proto(TS, p10), connected(p10, c10))), not(and(has_proto(TS, p11), connected(p11, c11))), not(and(has_proto(TS, p12), connected(p12, c12))), not(and(has_proto(TS, p13), connected(p13, c13))), not(and(has_proto(TS, p14), connected(p14, c14))).
% is_class(TS, c3) :- has_proto(TS, p3), connected(p3, c3), not(and(has_proto(TS, p0), connected(p0, c0))), not(and(has_proto(TS, p1), connected(p1, c1))), not(and(has_proto(TS, p2), connected(p2, c2))), not(and(has_proto(TS, p4), connected(p4, c4))), not(and(has_proto(TS, p5), connected(p5, c5))), not(and(has_proto(TS, p6), connected(p6, c6))), not(and(has_proto(TS, p7), connected(p7, c7))), not(and(has_proto(TS, p8), connected(p8, c8))), not(and(has_proto(TS, p9), connected(p9, c9))), not(and(has_proto(TS, p10), connected(p10, c10))), not(and(has_proto(TS, p11), connected(p11, c11))), not(and(has_proto(TS, p12), connected(p12, c12))), not(and(has_proto(TS, p13), connected(p13, c13))), not(and(has_proto(TS, p14), connected(p14, c14))).
% is_class(TS, c4) :- has_proto(TS, p4), connected(p4, c4), not(and(has_proto(TS, p0), connected(p0, c0))), not(and(has_proto(TS, p1), connected(p1, c1))), not(and(has_proto(TS, p2), connected(p2, c2))), not(and(has_proto(TS, p3), connected(p3, c3))), not(and(has_proto(TS, p5), connected(p5, c5))), not(and(has_proto(TS, p6), connected(p6, c6))), not(and(has_proto(TS, p7), connected(p7, c7))), not(and(has_proto(TS, p8), connected(p8, c8))), not(and(has_proto(TS, p9), connected(p9, c9))), not(and(has_proto(TS, p10), connected(p10, c10))), not(and(has_proto(TS, p11), connected(p11, c11))), not(and(has_proto(TS, p12), connected(p12, c12))), not(and(has_proto(TS, p13), connected(p13, c13))), not(and(has_proto(TS, p14), connected(p14, c14))).
% is_class(TS, c5) :- has_proto(TS, p5), connected(p5, c5), not(and(has_proto(TS, p0), connected(p0, c0))), not(and(has_proto(TS, p1), connected(p1, c1))), not(and(has_proto(TS, p2), connected(p2, c2))), not(and(has_proto(TS, p3), connected(p3, c3))), not(and(has_proto(TS, p4), connected(p4, c4))), not(and(has_proto(TS, p6), connected(p6, c6))), not(and(has_proto(TS, p7), connected(p7, c7))), not(and(has_proto(TS, p8), connected(p8, c8))), not(and(has_proto(TS, p9), connected(p9, c9))), not(and(has_proto(TS, p10), connected(p10, c10))), not(and(has_proto(TS, p11), connected(p11, c11))), not(and(has_proto(TS, p12), connected(p12, c12))), not(and(has_proto(TS, p13), connected(p13, c13))), not(and(has_proto(TS, p14), connected(p14, c14))).
% is_class(TS, c6) :- has_proto(TS, p6), connected(p6, c6), not(and(has_proto(TS, p0), connected(p0, c0))), not(and(has_proto(TS, p1), connected(p1, c1))), not(and(has_proto(TS, p2), connected(p2, c2))), not(and(has_proto(TS, p3), connected(p3, c3))), not(and(has_proto(TS, p4), connected(p4, c4))), not(and(has_proto(TS, p5), connected(p5, c5))), not(and(has_proto(TS, p7), connected(p7, c7))), not(and(has_proto(TS, p8), connected(p8, c8))), not(and(has_proto(TS, p9), connected(p9, c9))), not(and(has_proto(TS, p10), connected(p10, c10))), not(and(has_proto(TS, p11), connected(p11, c11))), not(and(has_proto(TS, p12), connected(p12, c12))), not(and(has_proto(TS, p13), connected(p13, c13))), not(and(has_proto(TS, p14), connected(p14, c14))).
% is_class(TS, c7) :- has_proto(TS, p7), connected(p7, c7), not(and(has_proto(TS, p0), connected(p0, c0))), not(and(has_proto(TS, p1), connected(p1, c1))), not(and(has_proto(TS, p2), connected(p2, c2))), not(and(has_proto(TS, p3), connected(p3, c3))), not(and(has_proto(TS, p4), connected(p4, c4))), not(and(has_proto(TS, p5), connected(p5, c5))), not(and(has_proto(TS, p6), connected(p6, c6))), not(and(has_proto(TS, p8), connected(p8, c8))), not(and(has_proto(TS, p9), connected(p9, c9))), not(and(has_proto(TS, p10), connected(p10, c10))), not(and(has_proto(TS, p11), connected(p11, c11))), not(and(has_proto(TS, p12), connected(p12, c12))), not(and(has_proto(TS, p13), connected(p13, c13))), not(and(has_proto(TS, p14), connected(p14, c14))).
% is_class(TS, c8) :- has_proto(TS, p8), connected(p8, c8), not(and(has_proto(TS, p0), connected(p0, c0))), not(and(has_proto(TS, p1), connected(p1, c1))), not(and(has_proto(TS, p2), connected(p2, c2))), not(and(has_proto(TS, p3), connected(p3, c3))), not(and(has_proto(TS, p4), connected(p4, c4))), not(and(has_proto(TS, p5), connected(p5, c5))), not(and(has_proto(TS, p6), connected(p6, c6))), not(and(has_proto(TS, p7), connected(p7, c7))), not(and(has_proto(TS, p9), connected(p9, c9))), not(and(has_proto(TS, p10), connected(p10, c10))), not(and(has_proto(TS, p11), connected(p11, c11))), not(and(has_proto(TS, p12), connected(p12, c12))), not(and(has_proto(TS, p13), connected(p13, c13))), not(and(has_proto(TS, p14), connected(p14, c14))).
% is_class(TS, c9) :- has_proto(TS, p9), connected(p9, c9), not(and(has_proto(TS, p0), connected(p0, c0))), not(and(has_proto(TS, p1), connected(p1, c1))), not(and(has_proto(TS, p2), connected(p2, c2))), not(and(has_proto(TS, p3), connected(p3, c3))), not(and(has_proto(TS, p4), connected(p4, c4))), not(and(has_proto(TS, p5), connected(p5, c5))), not(and(has_proto(TS, p6), connected(p6, c6))), not(and(has_proto(TS, p7), connected(p7, c7))), not(and(has_proto(TS, p8), connected(p8, c8))), not(and(has_proto(TS, p10), connected(p10, c10))), not(and(has_proto(TS, p11), connected(p11, c11))), not(and(has_proto(TS, p12), connected(p12, c12))), not(and(has_proto(TS, p13), connected(p13, c13))), not(and(has_proto(TS, p14), connected(p14, c14))).
% is_class(TS, c10) :- has_proto(TS, p10), connected(p10, c10), not(and(has_proto(TS, p0), connected(p0, c0))), not(and(has_proto(TS, p1), connected(p1, c1))), not(and(has_proto(TS, p2), connected(p2, c2))), not(and(has_proto(TS, p3), connected(p3, c3))), not(and(has_proto(TS, p4), connected(p4, c4))), not(and(has_proto(TS, p5), connected(p5, c5))), not(and(has_proto(TS, p6), connected(p6, c6))), not(and(has_proto(TS, p7), connected(p7, c7))), not(and(has_proto(TS, p8), connected(p8, c8))), not(and(has_proto(TS, p9), connected(p9, c9))), not(and(has_proto(TS, p11), connected(p11, c11))), not(and(has_proto(TS, p12), connected(p12, c12))), not(and(has_proto(TS, p13), connected(p13, c13))), not(and(has_proto(TS, p14), connected(p14, c14))).
% is_class(TS, c11) :- has_proto(TS, p11), connected(p11, c11), not(and(has_proto(TS, p0), connected(p0, c0))), not(and(has_proto(TS, p1), connected(p1, c1))), not(and(has_proto(TS, p2), connected(p2, c2))), not(and(has_proto(TS, p3), connected(p3, c3))), not(and(has_proto(TS, p4), connected(p4, c4))), not(and(has_proto(TS, p5), connected(p5, c5))), not(and(has_proto(TS, p6), connected(p6, c6))), not(and(has_proto(TS, p7), connected(p7, c7))), not(and(has_proto(TS, p8), connected(p8, c8))), not(and(has_proto(TS, p9), connected(p9, c9))), not(and(has_proto(TS, p10), connected(p10, c10))), not(and(has_proto(TS, p12), connected(p12, c12))), not(and(has_proto(TS, p13), connected(p13, c13))), not(and(has_proto(TS, p14), connected(p14, c14))).
% is_class(TS, c12) :- has_proto(TS, p12), connected(p12, c12), not(and(has_proto(TS, p0), connected(p0, c0))), not(and(has_proto(TS, p1), connected(p1, c1))), not(and(has_proto(TS, p2), connected(p2, c2))), not(and(has_proto(TS, p3), connected(p3, c3))), not(and(has_proto(TS, p4), connected(p4, c4))), not(and(has_proto(TS, p5), connected(p5, c5))), not(and(has_proto(TS, p6), connected(p6, c6))), not(and(has_proto(TS, p7), connected(p7, c7))), not(and(has_proto(TS, p8), connected(p8, c8))), not(and(has_proto(TS, p9), connected(p9, c9))), not(and(has_proto(TS, p10), connected(p10, c10))), not(and(has_proto(TS, p11), connected(p11, c11))), not(and(has_proto(TS, p13), connected(p13, c13))), not(and(has_proto(TS, p14), connected(p14, c14))).
% is_class(TS, c13) :- has_proto(TS, p13), connected(p13, c13), not(and(has_proto(TS, p0), connected(p0, c0))), not(and(has_proto(TS, p1), connected(p1, c1))), not(and(has_proto(TS, p2), connected(p2, c2))), not(and(has_proto(TS, p3), connected(p3, c3))), not(and(has_proto(TS, p4), connected(p4, c4))), not(and(has_proto(TS, p5), connected(p5, c5))), not(and(has_proto(TS, p6), connected(p6, c6))), not(and(has_proto(TS, p7), connected(p7, c7))), not(and(has_proto(TS, p8), connected(p8, c8))), not(and(has_proto(TS, p9), connected(p9, c9))), not(and(has_proto(TS, p10), connected(p10, c10))), not(and(has_proto(TS, p11), connected(p11, c11))), not(and(has_proto(TS, p12), connected(p12, c12))), not(and(has_proto(TS, p14), connected(p14, c14))).
% is_class(TS, c14) :- has_proto(TS, p14), connected(p14, c14), not(and(has_proto(TS, p0), connected(p0, c0))), not(and(has_proto(TS, p1), connected(p1, c1))), not(and(has_proto(TS, p2), connected(p2, c2))), not(and(has_proto(TS, p3), connected(p3, c3))), not(and(has_proto(TS, p4), connected(p4, c4))), not(and(has_proto(TS, p5), connected(p5, c5))), not(and(has_proto(TS, p6), connected(p6, c6))), not(and(has_proto(TS, p7), connected(p7, c7))), not(and(has_proto(TS, p8), connected(p8, c8))), not(and(has_proto(TS, p9), connected(p9, c9))), not(and(has_proto(TS, p10), connected(p10, c10))), not(and(has_proto(TS, p11), connected(p11, c11))), not(and(has_proto(TS, p12), connected(p12, c12))), not(and(has_proto(TS, p13), connected(p13, c13))).
